### ISSUE TITLE
Voiceprint Phrases

### ISSUE THREAD

**Issue by arkadybag** [voiceittech/voiceit-python#4]
Hello, say please, how i can get all **Voiceprint Phrases** from my developer console in API? 
I create wrapper around your service and i not know how me get all active phases

**SCREENSHOT**
![image](https://user-images.githubusercontent.com/16622328/35088082-86bcd32e-fc43-11e7-9d93-be1685302928.png)

Because user in my system will need select phase, which is approved VOICEIT. (it say in your FAQ page)

![image](https://user-images.githubusercontent.com/16622328/35088212-0db776f4-fc44-11e7-8a48-feaf40f65138.png)

**Comment by armaanbindra** [comment]
@arkadybag  please refrain from asking questions not directly related to our python wrapper as an issue on this repo. We would be happy to help you with any VoiceIt API integration questions if you reach out to as at support@voiceit.io. At the moment there are no API calls to receive the approved phrases. The way our API works, the user needs to be prompted to say the same phrase for the enrollment a minimum of three times and then again for authentication, thus, typically that just means you choosing one or a few phrases that are approved and use only those in your application, and you can store and prompt the user to say the phrases on your end. That said, we do have future plans in place as we build anew dashboard, to manage both API 1.0 and API 2.0 users, groups , activity, and phrases, along with with which there would most likely be a Dashboard API to be able to access the phrases approved for a developer account programatically.
